#jinja2:lstrip_blocks: True
---

fullnameOverride: "wiki"

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: "wiki.{{ domain }}"
      paths:
        - /
  tls:
    - secretName: wiki-tls-certificate
      hosts:
        - "wiki.{{ domain }}"

postgresql:
  {% if components.postgresql.enabled %}
  enabled: false
  postgresqlHost: postgresql.datastore.svc.cluster.local
  postgresqlUser: "{{ wiki_database_user }}"
  postgresqlDatabase: "{{ wiki_database_name }}"
  existingSecret: wiki-credentials
  existingSecretKey: postgresql-password
  {% else %}
  enabled: true
  {% endif %}
