---

- name: create namespaces
  community.kubernetes.k8s:
    context: "{{ context }}"
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
    state: present
  loop: "{{ kubernetes_namespaces + kubernetes_extra_namespaces }}"
  tags:
    - config

- name: delete namespaces
  community.kubernetes.k8s:
    context: "{{ context }}"
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
    state: absent
  loop: "{{ kubernetes_namespaces + kubernetes_extra_namespaces }}"
  tags:
    - never
    - purge
