---

fullnameOverride: "{{ release_name }}"

db:
  allowArbitraryServer: false
  port: 3306
  host: "mariadb-primary.datastore.svc.cluster.local"

ingress:
  enabled: true
  certManager: true
  rewriteTarget: true
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - name: "phpmyadmin.{{ domain }}"
      path: /
      tls: true
      tlsSecret: phpmyadmin-tls-certificate

metrics:
  enabled: {{ phpmyadmin_metrics_enabled }}
