---

fullnameOverride: "{{ release_name }}"

db:
  allowArbitraryServer: false
  host: "mariadb-primary.datastore.svc.cluster.local"

ingress:
  enabled: true
  certManager: true
  annotations:
    kubernetes.io/tls-acme: "true"
  hostname: "phpmyadmin.{{ domain }}"
  tls: true

metrics:
  enabled: {{ phpmyadmin_metrics_enabled }}
