---
- name: create namespaces
  community.kubernetes.k8s:
    context: "{{ context }}"
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
    state: present
  loop: "{{ kubernetes_namespaces + kubernetes_extra_namespaces }}"
  tags:
    - config

- name: Kubernetes - create service accounts
  community.kubernetes.k8s:
    context: "{{ context }}"
    api_version: v1
    kind: ServiceAccount
    name: "{{ item.name }}"
    namespace: "{{ item.namespace }}"
    state: present
  loop: "{{ kubernetes_service_accounts + kubernetes_extra_service_accounts }}"
  tags:
    - config

- name: Kubernetes - delete service accounts
  community.kubernetes.k8s:
    context: "{{ context }}"
    api_version: v1
    kind: ServiceAccount
    name: "{{ item.name }}"
    namespace: "{{ item.namespace }}"
    state: absent
  loop: "{{ kubernetes_service_accounts + kubernetes_extra_service_accounts }}"
  tags:
    - never
    - purge

- name: delete namespaces
  community.kubernetes.k8s:
    context: "{{ context }}"
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
    state: absent
  loop: "{{ kubernetes_namespaces + kubernetes_extra_namespaces }}"
  tags:
    - never
    - purge
