---

release_name: postgresql
release_namespace: datastore

chart_repository: https://charts.bitnami.com/bitnami
chart_name: postgresql
chart_version: 10.0.2

postgresql_admin_user: postgres
postgresql_admin_password:

postgresql_persistence_enabled: false
postgresql_persistence_size: 10Gi

postgresql_replication_enabled: false
postgresql_replication_user: repl
postgresql_replication_password:
