---

# Release information
release_name: postgresql
release_namespace: datastore

# Chart information
chart_repository: https://charts.bitnami.com/bitnami
chart_name: postgresql-ha
chart_version: 6.3.3

# PostgreSQL configuration
postgresql_admin_user: postgres
postgresql_admin_password:
postgresql_config_max_connections: 32
postgresql_config_shared_libraries: pgaudit,pg_stat_statements,repmgr
postgresql_metrics_enabled: true
postgresql_persistence_enabled: false
postgresql_persistence_size: 2Gi
postgresql_replication_user: replicator
postgresql_replication_password:
postgresql_replicas: 2

# pgpool configuration
pgpool_admin_user: pgpool
pgpool_admin_password:
pgpool_replicas: 1
