---
- set_fact:
    wait_completion: no
- set_fact:
    wait_completion: yes
  when: "components['{{ release_name | replace('-','_')}}']['wait']"

- name: create secrets
  community.kubernetes.k8s:
    context: "{{ context }}"
    template: templates/secrets.yaml
    state: present
  tags:
    - install

- name: deploy release
  community.kubernetes.helm:
    context: "{{ context }}"
    release_name: "{{ release_name }}"
    release_namespace: "{{ release_namespace }}"
    release_values: "{{ lookup('template', 'templates/values.yaml') | from_yaml }}"
    release_state: present
    chart_repo_url: "{{ chart_repository }}"
    chart_ref: "{{ chart_name }}"
    chart_version: "{{ chart_version }}"
    atomic: yes
    wait: "{{ wait_completion}}"
  tags:
    - install

- name: delete release
  community.kubernetes.helm:
    context: "{{ context }}"
    release_name: "{{ release_name }}"
    release_namespace: "{{ release_namespace }}"
    release_state: absent
  tags:
    - never
    - uninstall

- name: delete secrets
  community.kubernetes.k8s:
    context: "{{ context }}"
    template: templates/secrets.yaml
    state: absent
  tags:
    - never
    - uninstall
