
release_name: prometheus
release_namespace: monitoring

chart_repository: https://prometheus-community.github.io/helm-charts
chart_name: prometheus
prometheus_pushgateway_enabled: false
chart_version: 12.0.1
