---

# Release information
release_name: prometheus
release_namespace: monitoring

# Chart information
chart_repository: https://prometheus-community.github.io/helm-charts
chart_name: prometheus
chart_version: 12.0.1

# Main configuration
prometheus_pushgateway_enabled: false
