---

# Release information
release_name: prometheus
release_namespace: monitoring

# Chart information
chart_repository: https://prometheus-community.github.io/helm-charts
chart_name: prometheus
chart_version: 13.0.0

# prometheus configuration
## Modules settings
pushgateway_enabled: false
## Application settings
prometheus_evaluation_interval: 1m
prometheus_retention: 30d
prometheus_scrape_interval: 1m
prometheus_scrape_timeout: 10s
## Persistence settings
alertmanager_persistence_enabled: false
alertmanager_persistence_size: 2Gi
prometheus_persistence_enabled: false
prometheus_persistence_size: 2Gi
pushgateway_persistence_enabled: false
pushgateway_persistence_size: 2Gi
## Scaling settings
prometheus_replicas: 1
pushgateway_replicas: 1
