#jinja2:lstrip_blocks: True
---

fullnameOverride: traefik

deployment:
  replicas: 1
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8082"

podDisruptionBudget:
  enabled: true
  minAvailable: 1

ingressClass:
  enabled: true
  isDefaultClass: true

logs:
  access:
    enabled: true

additionalArguments:
  - "--entryPoints.metrics.address=:8082"
  - "--metrics.prometheus=true"
  - "--entrypoints.websecure.http.tls"
  - "--metrics.prometheus.addEntryPointsLabels=true"
  - "--metrics.prometheus.addServicesLabels=true"
  - "--metrics.prometheus.entryPoint=metrics"

ports:
  web:
    redirectTo: websecure

service:
  type : "{{ ingress_service_type }}"
  {% if ingress_service_type == 'LoadBalancer' %}
  spec:
    loadBalancerIP: "{{ ingress_service_ip }}"
  {% endif %}

priorityClassName: system-cluster-critical
