---

# Release information
release_name: cert-manager
release_namespace: kube-system

# Chart information
chart_repository: https://charts.jetstack.io
chart_name: cert-manager
chart_version: 1.1.0

# Main configuration
certmanager_log_level: 2
certmanager_metrics_enabled: true
certmanager_replicas: 1
