#jinja2:lstrip_blocks: True
---

fullnameOverride: "{{ release_name }}"

persistence:
  data:
    size: 5Gi
  plugins:
    size: 2Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    {% if components.oauth2_proxy.enabled %}
    nginx.ingress.kubernetes.io/auth-url: "https://auth.{{ domain }}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.{{ domain }}/oauth2/start?rd=https://$host$request_uri"
    {% endif %}
  hosts:
    - "mattermost.{{ domain }}"
  path: /
  tls:
    - secretName: mattermost-certificate
      hosts:
        - "mattermost.{{ domain }}"

externalDB:
  enabled: true
  externalDriverType: "postgres"
  externalConnectionString: "postgres://{{ mattermost_database_user }}:{{ mattermost_database_password }}@{{ mattermost_database_host | default('postgresql.datastore.svc.cluster.local') }}:5432/{{ mattermost_database_name }}?sslmode=disable&connect_timeout=10"

mysql:
  enabled: false

extraInitContainers:
  - name: change-folders-owners
    command:
    - sh
    - -c
    - chown -R 2000:2000 /mattermost/data /mattermost/plugins
    - chgrp 2000 /mattermost/data /mattermost/plugins
    image: busybox:latest
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mattermost/data
      name: mattermost-data
    - mountPath: /mattermost/plugins
      name: mattermost-plugins

configJSON: {
  "ServiceSettings": {
    "SiteURL": "https://mattermost.{{ domain }}",
    "EnableOAuthServiceProvider": true,
    "EnableOnlyAdminIntegrations": false,
    "EnableBotAccountCreation": true,
    "EnableDeveloper": true,
    "EnableMultifactorAuthentication": true,
    "EnforceMultifactorAuthentication": false,
    "WebsocketSecurePort": 443,
    "WebsocketPort": 80,
    "AllowCorsFrom": "*",
    "EnableCustomEmoji": true,
    "TimeBetweenUserTypingUpdatesMilliseconds": 1000,
  },
  "TeamSettings": {
    "SiteName": "{{ organization }}",
    "MaxUsersPerTeam": 50000,
    "EnableTeamCreation": true,
    "EnableUserCreation": true,
    "EnableOpenServer": true,
    "EnableCustomBrand": true,
    "CustomBrandText": "{{ organization }}",
    "CustomDescriptionText": "",
  },
  "PasswordSettings": {
    "MinimumLength": 10,
    "Lowercase": true,
    "Number": true,
    "Uppercase": true,
    "Symbol": true
  },
  "EmailSettings": {
    "EnableSignUpWithEmail": true,
    "EnableSignInWithEmail": true,
    "EnableSignInWithUsername": true,
    "SendEmailNotifications": false,
    "RequireEmailVerification": false,
    "SMTPUsername": "",
    "SMTPPassword": "",
    "EnableSMTPAuth": "",
    "SMTPServer": "",
    "SMTPPort": "",
    "SkipServerCertificateVerification": false
  },
  "RateLimitSettings": {
    "Enable": true,
  },
  "AnnouncementSettings": {
    "EnableBanner": true,
    "BannerText": "{{ organization }}",
    "AllowBannerDismissal": true
  }
}
