---

fullnameOverride: "{{ release_name }}"

global:
  priorityClassName: system-cluster-critical
  logLevel: 1

clusterResourceNamespace: "{{ release_namespace }}"
installCRDs: true

ingressShim:
  defaultIssuerName: "{{ 'selfsigned' if local else 'letsencrypt' }}"
  defaultIssuerKind: ClusterIssuer
  defaultIssuerGroup: cert-manager.io
