#jinja2:lstrip_blocks: True
---

fullnameOverride: "{{ release_name }}"

extraEnv:
  - name: HOSTS_TO_RESOLVE
    value: "{{ goldpinger_hosts | join(' ') }}"

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    {% if components.oauth2_proxy.enabled %}
    nginx.ingress.kubernetes.io/auth-url: "https://auth.{{ domain }}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.{{ domain }}/oauth2/start?rd=https://$host$request_uri"
    {% endif %}
  hosts:
    - "goldpinger.{{ domain }}"
  path: /
  tls:
    - secretName: goldpinger-tls-certificate
      hosts:
        - "goldpinger.{{ domain }}"
