---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-credentials
  namespace: "{{ release_namespace }}"
type: Opaque
data:
  mariadb-password: ""
  mariadb-replication-password: "{{ mariadb_replication_password | b64encode }}"
  mariadb-root-password: "{{ mariadb_root_password | b64encode }}"
