#jinja2:lstrip_blocks: True
---

fullnameOverride: "{{ release_name }}"
architecture: replication

auth:
  database: ""
  username: ""
  existingSecret: mariadb-credentials
  replicationUser: "{{ mariadb_replication_user }}"
  forcePassword: true
  usePasswordFiles: true

primary:
  {% if mariadb_persistence_enabled %}
  persistence:
    enabled: true
    size: "{{ mariadb_persistence_size }}"
  {% endif %}

secondary:
  replicaCount: "{{ mariadb_replicas }}"
  {% if mariadb_persistence_enabled %}
  persistence:
    enabled: true
    size: "{{ mariadb_persistence_size }}"
  {% endif %}

rbac:
  create: true

volumePermissions:
  enabled: false

{% if mariadb_metrics_enabled %}
metrics:
  enabled: true
{% endif %}
