#jinja2:lstrip_blocks: True
---

fullnameOverride: "{{ release_name }}"

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    {% if components.oauth2_proxy.enabled %}
    nginx.ingress.kubernetes.io/auth-url: "https://auth.{{ domain }}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.{{ domain }}/oauth2/start?rd=https://$host$request_uri"
    {% endif %}
  hosts:
    - host: "wiki.{{ domain }}"
      paths:
        - /
  tls:
    - secretName: wiki-tls-certificate
      hosts:
        - "wiki.{{ domain }}"

postgresql:
  {% if components.postgresql.enabled or wikijs_database_host %}
  enabled: false
  postgresqlHost: "{{ wikijs_database_host | default('postgresql.datastore.svc.cluster.local') }}"
  postgresqlUser: "{{ wikijs_database_user }}"
  postgresqlDatabase: "{{ wikijs_database_name }}"
  existingSecret: wikijs-credentials
  existingSecretKey: postgresql-password
  {% else %}
  enabled: true
  {% endif %}
