---

# Release information
release_name: oauth2-proxy
release_namespace: kube-system

# Chart information
chart_repository: https://k8s-at-home.com/charts/
chart_name: oauth2-proxy
chart_version: 4.0.1

# Main configuration
oauth2_proxy_provider: google
oauth2_proxy_client_id: id
oauth2_proxy_client_secret: secret
oauth2_proxy_cookie_secret: cookie
oauth2_proxy_email_domains: "*"
oauth2_proxy_service_account:
oauth2_proxy_replicas: 1
