#jinja2:lstrip_blocks: True
---

fullnameOverride: "{{ release_name }}"

controller:
  config:
    {% for option in ingress_nginx_config %}
    {{ option }}: "{{ nginx_config[option] }}"
    {% endfor %}
  replicaCount: "{{ ingress_replicas }}"
  service:
    type: "{{ ingress_service_type }}"
    {% if ingress_service_type == 'LoadBalancer' and ingress_service_ip %}
    loadBalancerIP: "{{ ingress_service_ip }}"
    {% endif %}
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

  priorityClassName: "system-cluster-critical"

podSecurityPolicy:
  enabled: true
