#jinja2:lstrip_blocks: True
---

fullnameOverride: prometheus

alertmanager:
  baseURL: "https://alertmanager.{{ domain }}"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - "alertmanager.{{ domain }}"
    tls:
      - secretName: alertmanager-tls-certificate
        hosts:
          - "alertmanager.{{ domain }}"
  persistentVolume:
    enabled: {{ alertmanager_persistence_enabled }}
    size: "{{ alertmanager_persistence_size }}"

server:
  baseURL: "https://prometheus.{{ domain }}"
  extraFlags:
    - storage.tsdb.wal-compression
    - web.enable-lifecycle
  global:
    scrape_interval: "{{ prometheus_scrape_interval }}"
    scrape_timeout: "{{ prometheus_scrape_timeout }}"
    evaluation_interval: "{{ prometheus_evaluation_interval }}"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - "prometheus.{{ domain }}"
    tls:
      - secretName: prometheus-tls-certificate
        hosts:
          - "prometheus.{{ domain }}"
  persistentVolume:
    enabled: {{ prometheus_persistence_enabled }}
    size: "{{ prometheus_persistence_size }}"
  replicaCount: "{{ prometheus_replicas }}"
  retention: "{{ prometheus_retention }}"

pushgateway:
  enabled: {{ pushgateway_enabled }}
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - "pushgateway.{{ domain }}"
    tls:
      - secretName: pushgateway-tls-certificate
        hosts:
          - "pushgateway.{{ domain }}"
  replicaCount: "{{ pushgateway_replicas }}"
  persistentVolume:
    enabled: {{ pushgateway_persistence_enabled }}
    size: "{{ pushgateway_persistence_size }}"

alertmanagerFiles:
  alertmanager.yml:
    global: {}
    receivers:
      - name: default-receiver
    route:
      group_wait: 10s
      group_interval: 5m
      receiver: default-receiver
      repeat_interval: 3h

serverFiles:
  alerting_rules.yml: {}
  recording_rules.yml: {}
  prometheus.yml:
    rule_files:
      - /etc/config/recording_rules.yml
      - /etc/config/alerting_rules.yml

extraScrapeConfigs:
