#jinja2:lstrip_blocks: True
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: "{{ release_namespace }}"
type: Opaque
data:
  postgresql-password: "{{ postgresql_admin_password | b64encode }}"
  {% if postgresql_replication_enabled %}
  postgresql-replication-password: "{{ postgresql_replication_password | b64encode }}"
  {% endif %}
