---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: "{{ release_namespace }}"
type: Opaque
data:
  postgresql-password: "{{ postgresql_admin_password | b64encode }}"
  repmgr-password: "{{ postgresql_replication_password | b64encode }}"
