#jinja2:lstrip_blocks: True
---

fullnameOverride: "{{ release_name }}"

{% if postgresql_replication_enabled %}
replication:
  enabled: true
  user: "{{ postgresql_replication_user }}"
  password: "{{ postgresql_replication_password }}"
  readReplicas: {{ postgresql_replicas }}
  applicationName: postgres
{% endif %}

postgresqlUsername: "{{ postgresql_admin_user }}"
existingSecret: postgresql-credentials
usePasswordFile: true
postgresqlDatabase: postgres

initdbScripts:
  init_databases.sql: |
  {% for variable in (lookup('varnames', '.+_database_name$')).split(',') %}
    {% set component = variable.split('_')[0] %}
    create role {{ vars[component + '_database_user'] }} with login encrypted password '{{ vars[component + '_database_password'] }}';
    create database {{ component }} with owner {{ vars[component + '_database_user'] }};
  {% endfor %}

initdbUser: "{{ postgresql_admin_user }}"
initdbPassword: "{{ postgresql_admin_password }}"

postgresqlSharedPreloadLibraries: "{{ postgresql_config_shared_libraries }}"
postgresqlMaxConnections: "{{ postgresql_config_max_connections }}"

persistence:
  enabled: "{{ postgresql_persistence_enabled }}"
  size: "{{ postgresql_persistence_size }}"

metrics:
  enabled: {{ postgresql_metrics_enabled }}
