#jinja2:lstrip_blocks: True
---

fullnameOverride: postgresql

{% if postgresql_replication_enabled %}
replication:
  enabled: true
  user: "{{ postgresql_replication_user }}"
  password: "{{ postgresql_replication_password }}"
  readReplicas: 1
  applicationName: postgres
{% endif %}

postgresqlUsername: "{{ postgresql_admin_user }}"
existingSecret: postgresql-credentials
usePasswordFile: true
postgresqlDatabase: postgres

postgresqlSharedPreloadLibraries: "{{ postgresql_shared_libraries }}"
postgresqlMaxConnections: "{{ postgresql_max_connections }}"

persistence:
  enabled: "{{ postgresql_persistence_enabled }}"
  size: "{{ postgresql_persistence_size }}"

metrics:
  enabled: true
