---

fullnameOverride: redis

cluster:
  enabled: true
  slaveCount: "{{ redis_replicas }}"

sentinel:
  enabled: true
  usePassword: true
  masterSet: "{{ redis_master_set }}"
  quorum: "{{ redis_quorum }}"
  staticID: true

usePassword: false

{% if redis_persistence_enabled %}
slave:
  persistence:
    enabled: true
    size: "{{ redis_persistence_size }}"
{% endif %}

metrics:
  enabled: true

sysctlImage:
  enabled: true
