---
# Release information
release_name: harbor
release_namespace: automation

# Chart information
chart_repository: https://helm.goharbor.io
chart_name: harbor
chart_version: 1.5.2

# Main configuration
harbor_ingress_controller: default

