---
# Release information
release_name: harbor
release_namespace: deployment

# Chart information
chart_repository: https://helm.goharbor.io
chart_name: harbor
chart_version: 1.5.2

# harbor configuration
## Module settings
harbor_chartmuseum_enabled: false
harbor_clair_enabled: false
harbor_notary_enabled: false
harbor_persistence_enabled: false
harbor_trivy_enabled: true
## Administrator credentials
harbor_admin_password: harbor
harbor_secret_key: AfAdutIdnecoyheu
## Database settings
harbor_database_type: external
harbor_database_host: postgresql-pgpool.datastore.svc.cluster.local
harbor_database_name: harbor
harbor_database_user: harbor
harbor_database_password: harbor
## Redis settings
harbor_redis_type: external
harbor_redis_host: redis.datastore.svc.cluster.local
harbor_redis_port: 26379
## Registry settings
harbor_registry_user: harbor_registry_user
harbor_registry_password: harbor_registry_password
### If you update the username or password of registry, make sure use cli tool htpasswd to generate the bcrypt hash
### e.g. "htpasswd -nbBC10 $username $password"
harbor_registry_ht_password: harbor_registry_user:$2y$10$9L4Tc0DJbFFMB6RdSCunrOpTHdwhid4ktBJmLD00bYgqkkGOvll3m
registry_database_name: registry
registry_database_user: harbor
registry_database_password: harbor
## Clair settings
clair_database_name: clair
clair_database_user: harbor
clair_database_password: harbor
## Persistence settings
harbor_persistence_chartmuseum_size: 2Gi
harbor_persistence_database_size: 2Gi
harbor_persistence_jobservice_size: 2Gi
harbor_persistence_redis_size: 2Gi
harbor_persistence_registry_size: 2Gi
harbor_persistence_trivy_size: 2Gi
