---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: "{{ release_namespace }}"
type: Opaque
data:
  rabbitmq-password: "{{ rabbitmq_admin_password | b64encode }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-erlang-cookie
  namespace: "{{ release_namespace }}"
type: Opaque
data:
  rabbitmq-erlang-cookie: "{{ rabbitmq_erlang_cookie | b64encode }}"
