---
apiVersion: v1
kind: Secret
metadata:
  name: rundeck-credentials
  namespace: "{{ release_namespace }}"
type: Opaque
data:
  RUNDECK_DATABASE_PASSWORD: "{{ rundeck_database_password | b64encode }}"
