#jinja2:lstrip_blocks: True
---

fullnameOverride: "{{ release_name }}"

deployment:
  replicaCount: 1

rundeck:
  env:
    RUNDECK_GRAILS_URL: "https://rundeck.{{ domain }}/"
    RUNDECK_SERVER_FORWARDED: "false"
    RUNDECK_DATABASE_DRIVER: org.postgresql.Driver
    RUNDECK_DATABASE_USERNAME: "{{ rundeck_database_user }}"
    RUNDECK_DATABASE_URL: "jdbc:postgresql://{{ rundeck_database_host | default('postgresql.datastore.svc.cluster.local') }}/{{ rundeck_database_name }}"
  envSecret: "rundeck-credentials"

persistence:
  enabled: "{{ rundeck_persistence_enabled }}"
  claim:
    create: true
    accessMode: ReadWriteOnce
    size: "{{ rundeck_persistence_size }}"

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    {% if components.oauth2_proxy.enabled %}
    nginx.ingress.kubernetes.io/auth-url: "https://auth.{{ domain }}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.{{ domain }}/oauth2/start?rd=https://$host$request_uri"
    {% endif %}
  paths:
    - /
  hosts:
    - "rundeck.{{ domain }}"
  tls:
    - secretName: rundeck-tls-certificate
      hosts:
        - "rundeck.{{ domain }}"
