---
all:
  hosts:
    local:
      local: true
    development:
      local: false
    staging:
      local: false
    production:
      local: false
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3
