#jinja2:lstrip_blocks: True
---

fullnameOverride: "{{ release_name }}"

dokuwikiUsername: "{{ dokuwiki_admin_user }}"
existingSecret: "dokuwiki-credentials"
dokuwikiEmail: "{{ dokuwiki_admin_email }}"
dokuwikiFullName: "{{ dokuwiki_admin_name }}"
dokuwikiWikiName: "{{ organization}} - DokuWiki"

service:
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - name: "dokuwiki.{{ domain }}"
      tls: true
      certManager: true
      tlsSecret: dokuwiki-tls-certificate
      annotations:
        kubernetes.io/tls-acme: "true"
        {% if components.oauth2proxy.enabled %}
        nginx.ingress.kubernetes.io/auth-url: "https://auth.{{ domain }}/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.{{ domain }}/oauth2/start?rd=https://$host$request_uri"
        {% endif %}

persistence:
  enabled: "{{ dokuwiki_persistence_enabled }}"
  size: "{{ dokuwiki_persistence_size }}"

volumePermissions:
  enabled: true

metrics:
  enabled: "{{ dokuwiki_metrics_enabled }}"
