---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: "{{ release_namespace }}"
type: Opaque
data:
  admin-user: "{{ grafana_admin_user | b64encode }}"
  admin-password: "{{ grafana_admin_password | b64encode }}"
{% if grafana_oauth_enabled %}
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth-credentials
  namespace: "{{ release_namespace }}"
type: Opaque
data:
  GF_AUTH_GOOGLE_CLIENT_ID: "{{ grafana_oauth_client_id | b64encode }}"
  GF_AUTH_GOOGLE_CLIENT_SECRET: "{{ grafana_oauth_client_secret | b64encode }}"
{% endif %}
