#jinja2:lstrip_blocks: True
---

fullnameOverride: "{{ release_name }}"

config:
  existingSecret: oauth2-proxy-credentials
  {% if oauth2_proxy_service_account %}
  google:
    existingSecret: oauth2-proxy-credentials
  {% endif %}
  configFile: |-
    email_domains = [ "{{ email_domain }}" ]

extraArgs:
  cookie-domain: ".{{ domain }}"
  pass-access-token: true
  whitelist-domain: ".{{ domain }}"

ingress:
  enabled: true
  hosts:
    - "auth.{{ domain }}"
  path: /
  annotations:
    kubernetes.io/tls-acme: "true"
  tls:
    - secretName: oauth2-proxy-tls-certificate
      hosts:
        - "auth.{{ domain }}"

replicaCount: "{{ oauth2_proxy_replicas }}"

httpScheme: http
