---

- hosts: all
  vars_files:
    - "../configurations/{{ inventory_hostname }}.context.yaml"
  pre_tasks:
    - name: define roles based on components
      set_fact:
        roles: "{{ components | dict2items | selectattr('value.enabled', 'equalto', true) | sort(attribute='value.priority') }}"
      tags:
        - always
    - name: check only one ingress controller is enabled
      meta: end_play
      when: roles | selectattr('value.type', 'equalto', 'ingress') | count > 1
      tags:
        - always
  tasks:
    - name: include role
      include_role:
        name: "{{ item.value.type }}/{{ item.key }}"
      tags:
        - install
        - uninstall
      loop: "{{ roles }}"
