---

# Release information
release_name: rabbitmq
release_namespace: messaging

# Chart information
chart_repository: https://charts.bitnami.com/bitnami
chart_name: rabbitmq
chart_version: 8.6.1

# rabbitmq configuration
## Administrator credentials
rabbitmq_admin_user: admin
rabbitmq_admin_password: admin
## Application settings
rabbitmq_erlang_cookie: Vap3quennubdabAm
rabbitmq_plugins:
  - rabbitmq_management
  - rabbitmq_peer_discovery_k8s
## Persistence settings
rabbitmq_persistence_enabled: false
rabbitmq_persistence_size: 2Gi
## Scaling settings
rabbitmq_replicas: 1
